import type { Metadata } from "next";
import { Englebert, Geist_Mono } from "next/font/google";
import "./globals.css";

const englebert = Englebert({
  variable: "--font-englebert",
  subsets: ["latin"],
  weight: ["400"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${englebert.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
